=== Immortalin/ExiL/3rd-side/albert-0.4.10/data/api.dtd
<!--
      DTD for specifying XML APIs in the Software Documentation
      System (SDS) developed and written by
      Stig E. Sandoe <stig@ii.uib.no>

      Last updated: Dec 2000
      
-->


<!ENTITY % text " #PCDATA ">

<!ELEMENT api (constant*,class+)>
<!ATTLIST api name CDATA #REQUIRED>

<!ELEMENT constant EMPTY>
<!ATTLIST constant
     name CDATA ""
     val  CDATA ""
     >

<!ELEMENT class (doc?,var*,attr*,subelem*)>
<!ATTLIST class
     name    CDATA ""
     elmname CDATA ""
     >

<!ELEMENT var EMPTY>
<!ATTLIST var
     name CDATA ""
     type CDATA ""
     doc  CDATA ""
     >
    
<!ELEMENT attr EMPTY>
<!ATTLIST attr
     name CDATA ""
     type CDATA ""
     var  CDATA ""
     doc  CDATA ""
     >

<!ELEMENT subelem EMPTY>
<!ATTLIST subelem
     name CDATA ""
     type CDATA ""
     var  CDATA ""
     doc  CDATA ""
     >
     
<!ELEMENT doc (%text)>

=== Immortalin/ExiL/3rd-side/albert/data/apis/modapi.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE api SYSTEM "api.dtd">

<api name="ModSpec">

  <constant name="MODULES"  val="modules"/>
  <constant name="MODULE"   val="module"/>
  <constant name="PACKAGE"  val="package"/>
  <constant name="INFO"     val="info"/>

  <constant name="CATEGORY" val="category"/>
  <constant name="DESC"     val="desc"/>
  
  <constant name="SCOPE"  val="scope"/>
  <constant name="FILE"   val="file"/>
  <constant name="DIR"    val="dir"/>
  <constant name="PREFIX" val="prefix"/>
  <constant name="CLASS"  val="class"/>
  <constant name="DOC"            val="doc"/>
  <constant name="TEXT"           val="text"/>


<!-- the classes... -->

  <class name="TopLevel" elmname="modules"> 
    <var type="ptrlist" name="modules"/>
    <subelem type="ptrlist" name="module" var="modules"/>
    <subelem type="ptrlist" name="package" var="modules"/>
  </class>
      
  <class name="Category" elmname="category">
     <var type="string" name="name"/>
     <var type="string" name="desc"/>
     <var type="ptrlist" name="scopes"/>
     
     <attr    type="string"  name="name"  var="name"/>
     <subelem type="string"  name="desc"  var="desc"/>
     <subelem type="ptrlist" name="scope" var="scopes"/>
  </class>
  
  <class name="Module" elmname="module">
    <var type="string" name="name"/>
    <var type="string" name="fullname"/>
    <var type="ptrlist" name="info"/>
    <var type="ptr" name="scope"/>
    <var type="ptrlist" name="categories"/>
    
    <attr    type="string"  name="name"     var="name"/>
    <attr    type="string"  name="fullname" var="fullname"/>
    <subelem type="ptrlist" name="info"     var="info"/>
    <subelem type="ptr"     name="scope"    var="scope"/>
    <subelem type="ptrlist" name="category" var="categories"/>
  </class>
  
  <class name="Package" elmname="package">
    <var type="string"  name="name"/>
    <var type="ptrlist" name="doc"/>
    <var type="ptrlist" name="info"/>
    <var type="ptrlist" name="categories"/>
    
    <attr    type="string"  name="name"     var="name"/>
    <subelem type="ptrlist" name="doc"     var="doc"/>
    <subelem type="ptrlist" name="info"     var="info"/>
    <subelem type="ptrlist" name="category" var="categories"/>
  </class>  

  <class name="Scope" elmname="scope">
    <var type="stringlist" name="files"/>
    <var type="stringlist" name="directories"/>
    <var type="stringlist" name="prefixes"/>
    <var type="stringlist" name="classes"/>
    
    <subelem type="stringlist" name="file"   var="files"/>
    <subelem type="stringlist" name="dir"    var="directories"/>
    <subelem type="stringlist" name="prefix" var="prefixes"/>
    <subelem type="stringlist" name="class"  var="classes"/>
  </class>    

  <class name="Info" elmname="info">
    <var type="string" name="type"/>
    <var type="string" name="value"/>
    <var type="string" name="info"/>
    
    <attr type="string"  name="type"  var="type"/>
    <attr type="string"  name="value" var="value"/>
    <attr type="string"  name="info"  var="info"/>
  </class>

    <!-- should have #pcdata instead of a text-element -->
  <class name="Doc" elmname="doc">
    <var type="string"  name="type"/>
    <var type="string"  name="text"/>

    <attr    type="string"   name="type"    var="type"/>
    <subelem type="string"   name="text"    var="text"/>
  </class>

  
</api>

=== Immortalin/ExiL/backup/3rd-side/albert/data/apis/csfapi.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE api SYSTEM "api.dtd">

<api name="CSF">

  <constant name="CSF"            val="csf"/>
  <constant name="LOCATION"       val="location"/>
  <constant name="PACKAGE"        val="package"/>
  <constant name="INFO"           val="info"/>
  <constant name="CLASS"          val="class"/>
  <constant name="METHOD"         val="method"/>

  <constant name="WHERE"          val="where"/>
  <constant name="RETVAL"         val="retval"/>
  <constant name="ARG"            val="arg"/>
  <constant name="VARIABLE"       val="variable"/>
  <constant name="ENUM"           val="enum"/>
  <constant name="ENUMVAL"        val="enumval"/>
  <constant name="TYPESPEC"       val="typespec"/>
  <constant name="ACCESS"         val="access"/>
  <constant name="INHERIT"        val="inherit"/>
  <constant name="COMMENT"        val="comment"/>
  <constant name="DIRECTIVE"      val="directive"/>
  <constant name="TEXT"           val="text"/>

  <class name="Toplevel" elmname="csf">
    <var type="string"  name="language"/>
    <var type="ptrlist" name="content"/>

    <attr    type="string"   name="language" var="language"/>
    
    <subelem type="ptrlist" name="package"   var="content"/>
    <subelem type="ptrlist" name="method"    var="content"/>
    <subelem type="ptrlist" name="class"     var="content"/>
    <subelem type="ptrlist" name="enum"      var="content"/>
    <subelem type="ptrlist" name="variable"  var="content"/>
    <subelem type="ptrlist" name="typespec"  var="content"/>
    <subelem type="ptrlist" name="comment"   var="content"/>
    <subelem type="ptrlist" name="directive" var="content"/>
  </class>

  <class name="Package" elmname="package">
    <var type="string"  name="id"/>
    <var type="string"  name="name"/>
    <var type="ptr"     name="location"/>
    <var type="ptrlist" name="info"/>
    <var type="ptrlist" name="content"/>

    <attr    type="string"   name="id" var="id"/>
    <attr    type="string"   name="name" var="name"/>

    <subelem type="ptr"      name="location"  var="location"/>
    <subelem type="ptrlist"  name="info"      var="info"/>
    
    <subelem type="ptrlist" name="package"   var="content"/>
    <subelem type="ptrlist" name="method"    var="content"/>
    <subelem type="ptrlist" name="class"     var="content"/>
    <subelem type="ptrlist" name="enum"      var="content"/>
    <subelem type="ptrlist" name="variable"  var="content"/>
    <subelem type="ptrlist" name="typespec"  var="content"/>
    <subelem type="ptrlist" name="comment"   var="content"/>
    <subelem type="ptrlist" name="directive" var="content"/>
    
  </class>

  <class name="Class" elmname="class">
    <var type="string"   name="id"/>
    <var type="string"   name="name"/>
    <var type="ptr"      name="location"/>
    <var type="ptr"      name="access"/>
    <var type="ptrlist"  name="parents"/>
    <var type="ptrlist"  name="info"/>
    <var type="ptrlist"  name="content"/>

    <attr    type="string"   name="id" var="id"/>
    <attr    type="string"   name="name" var="name"/>

    <subelem type="ptr"      name="location"  var="location"/>
    <subelem type="ptr"      name="access"    var="access"/>
    <subelem type="ptrlist"  name="inherit"   var="parents"/>
    <subelem type="ptrlist"  name="info"      var="info"/>
    
    <subelem type="ptrlist" name="package"   var="content"/>
    <subelem type="ptrlist" name="method"    var="content"/>
    <subelem type="ptrlist" name="class"     var="content"/>
    <subelem type="ptrlist" name="enum"      var="content"/>
    <subelem type="ptrlist" name="variable"  var="content"/>
    <subelem type="ptrlist" name="typespec"  var="content"/>
    <subelem type="ptrlist" name="comment"   var="content"/>
    <subelem type="ptrlist" name="directive" var="content"/>
    
  </class>


  <class name="Method" elmname="method">
    <var type="string"  name="id"/>
    <var type="string"  name="name"/>
    <var type="ptrlist" name="where"/>
    <var type="ptr"     name="access"/>
    <var type="ptrlist" name="info"/>
    <var type="ptrlist" name="retvals"/>
    <var type="ptrlist" name="args"/>
    <var type="ptrlist"  name="content"/>


    <attr    type="string"   name="id" var="id"/>
    <attr    type="string"   name="name" var="name"/>

    <subelem type="ptrlist"  name="where"     var="where"/>
    <subelem type="ptr"      name="access"    var="access"/>
    <subelem type="ptrlist"  name="info"      var="info"/>
    <subelem type="ptrlist"  name="retval"    var="retvals"/>
    <subelem type="ptrlist"  name="arg"       var="args"/>

    <subelem type="ptrlist" name="package"   var="content"/>
    <subelem type="ptrlist" name="method"    var="content"/>
    <subelem type="ptrlist" name="class"     var="content"/>
    <subelem type="ptrlist" name="enum"      var="content"/>
    <subelem type="ptrlist" name="variable"  var="content"/>
    <subelem type="ptrlist" name="typespec"  var="content"/>
    <subelem type="ptrlist" name="comment"   var="content"/>
    <subelem type="ptrlist" name="directive" var="content"/>
   </class>  

  <class name="Variable" elmname="variable">
    <var type="string"  name="id"/>
    <var type="string"  name="name"/>
    <var type="ptr"     name="location"/>
    <var type="ptr"     name="access"/>
    <var type="ptrlist" name="info"/>

    <attr    type="string"   name="id" var="id"/>
    <attr    type="string"   name="name" var="name"/>
    
    <subelem type="ptr"      name="location"  var="location"/>
    <subelem type="ptr"      name="access"    var="access"/>
    <subelem type="ptrlist"  name="info"      var="info"/>
  </class>  

  <class name="Enum" elmname="enum">
    <var type="string"  name="id"/>
    <var type="string"  name="name"/>
    <var type="ptr"     name="location"/>
    <var type="ptr"     name="access"/>
    <var type="ptrlist" name="values"/>

    <attr    type="string"   name="id" var="id"/>
    <attr    type="string"   name="name" var="name"/>
    
    <subelem type="ptr"      name="location"  var="location"/>
    <subelem type="ptr"      name="access"    var="access"/>
    <subelem type="ptrlist"  name="enumval"   var="values"/>
  </class>
  
  <class name="Enumval" elmname="enumval">
    <var type="string" name="name"/>
    <var type="string" name="value"/>
    <attr type="string"  name="name"  var="name"/>
    <attr type="string"  name="value" var="value"/>
  </class>
  
  <class name="TypeSpec" elmname="typespec">
    <var type="string"  name="id"/>
    <var type="string"  name="name"/>
    <var type="ptr"     name="location"/>
    <var type="ptr"     name="access"/>
    <var type="ptrlist" name="info"/>

    <attr    type="string"   name="id"      var="id"/>
    <attr    type="string"   name="name"    var="name"/>
    
    <subelem type="ptr"      name="location"  var="location"/>
    <subelem type="ptr"      name="access"    var="access"/>
    <subelem type="ptrlist"  name="info"      var="info"/>
  </class>

  <class name="Comment" elmname="comment">
    <var type="ptr"     name="location"/>
    <var type="string"  name="text"/>

    <subelem type="ptr"      name="location"  var="location"/>
    <subelem type="string"   name="text"      var="text"/>
  </class>
  
  <class name="Directive" elmname="directive">
    <var type="string"  name="name"/>
    <var type="string"  name="value"/>
    <var type="string"  name="info"/>
    <var type="ptr"     name="location"/>

    <attr    type="string"   name="name" var="name"/>
    <attr    type="string"   name="info" var="info"/>
    <attr    type="string"   name="value" var="value"/>
    
    <subelem type="ptr"      name="location"  var="location"/>
  </class>
    
  <class name="Retval" elmname="retval">
    <var     type="ptrlist" name="info"/>
    <subelem type="ptrlist" name="info" var="info"/>
  </class>

  <class name="Arg" elmname="arg">
    <var     type="ptrlist" name="info"/>
    <subelem type="ptrlist" name="info" var="info"/>
  </class>
    
  <class name="Info" elmname="info">
    <var type="string" name="type"/>
    <var type="string" name="value"/>
    <var type="string" name="info"/>
    <attr type="string"  name="type"  var="type"/>
    <attr type="string"  name="value" var="value"/>
    <attr type="string"  name="info"  var="info"/>
  </class>

  <class name="Access" elmname="access">
    <var type="string" name="visibility"/>
    <var type="string" name="scope"/>
    <attr type="string"  name="visibility"  var="visibility"/>
    <attr type="string"  name="scope"       var="scope"/>
  </class>

  <!-- name can also be an id -->
  <class name="Inherit" elmname="inherit">
    <var type="string"  name="name"/>
    <var type="ptrlist" name="info"/>
    <attr    type="string"  name="name" var="name"/>
    <subelem type="ptrlist" name="info" var="info"/>
  </class>

  <class name="Where" elmname="where">
    <var type="string"  name="what"/>
    <var type="ptr"     name="location"/>

    <attr    type="string"   name="what" var="what"/>
    <subelem type="ptr"      name="location"  var="location"/>
  </class>
    
  
  <class name="Location" elmname="location">
    <var type="string" name="file"/>
    <var type="string" name="startline"/>
    <var type="string" name="startcol"/>
    <var type="string" name="endline"/>
    <var type="string" name="endcol"/>
    <var type="string" name="position"/>
    <attr type="string"  name="file"      var="file"/>
    <attr type="string"  name="startline" var="startline"/>
    <attr type="string"  name="startcol"  var="startcol"/>
    <attr type="string"  name="endline"   var="endline"/>
    <attr type="string"  name="endcol"    var="endcol"/>
    <attr type="string"  name="position"  var="position"/>
  </class>

  
</api>

=== Immortalin/ExiL/3rd-side/albert-0.4.10/data/apis/apiapi.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE api SYSTEM "api.dtd">

<api name="ApiSpec">

  <constant name="API"      val="api"/>
  <constant name="CONSTANT" val="constant"/>
  <constant name="CLASS"    val="class"/>
  <constant name="VAR"      val="var"/>
  <constant name="ATTR"     val="attr"/>
  <constant name="SUBELEM"  val="subelem"/>
  <constant name="DOC"      val="doc"/>
  <constant name="INFODOC"  val="infodoc"/>
  <constant name="EXPL"     val="expl"/>

  
  <class name="TopLevel" elmname="api">
    <var type="string"  name="name"/>
    <var type="ptrlist" name="constants"/>
    <var type="ptrlist" name="classes"/>
    
    <attr    type="string"  name="name"     var="name"/>
    <subelem type="ptrlist" name="constant" var="constants"/>
    <subelem type="ptrlist" name="class"    var="classes"/>
  </class>  

  <class name="Constant" elmname="constant">
    <var type="string" name="name"/>
    <var type="string" name="val"/>
    
    <attr type="string"  name="name"  var="name"/>
    <attr type="string"  name="val"   var="val"/>
  </class>  

  <class name="Class" elmname="class">
    <doc>This element describes a class-abstraction and is represented
      as an element in XML</doc>
    
    <var type="string"  name="name"/>
    <var type="string"  name="elmname"/>
    <var type="string"  name="doc"/>
    <var type="ptrlist" name="vars"/>
    <var type="ptrlist" name="attrs"/>
    <var type="ptrlist" name="subelems"/>
    <var type="ptrlist" name="infodoc"/>
    
    <attr    type="string"  name="name"    var="name"/>
    <attr    type="string"  name="elmname" var="elmname"/>
    <subelem type="string"  name="doc"     var="doc"/>
    <subelem type="ptrlist" name="var"     var="vars"/>
    <subelem type="ptrlist" name="attr"    var="attrs"/>
    <subelem type="ptrlist" name="subelem" var="subelems"/>
    <subelem type="ptrlist" name="infodoc" var="infodoc"/>
  </class>  
    
  <class name="Var" elmname="var">
    <doc>This is a variable within a class which is a placeholder for
    the data for one or more attributes and/or subelements</doc>
    
    <var type="string" name="name"/>
    <var type="string" name="type"/>
    <var type="string"  name="doc"/>
    <attr type="string"  name="name" var="name"/>
    <attr type="string"  name="type" var="type"/>
    <attr type="string"  name="doc"  var="doc"/>
  </class>  

  <class name="Attr" elmname="attr">
    <doc>This is information about a legal attribute for a class.</doc>
    <var type="string" name="name"/>
    <var type="string" name="type"/>
    <var type="string" name="var"/>
    <var type="string"  name="doc"/>
    
    <attr type="string"  name="name" var="name"/>
    <attr type="string"  name="type" var="type"/>
    <attr type="string"  name="var"  var="var"/>
    <attr type="string"  name="doc"  var="doc"/>
  </class>  

  <class name="SubElem" elmname="subelem">
    <doc>This is information about a legal subelement for a
    class/element.  The name should have a matching global constant to
    make lookups and code faster.</doc>
    
    <var type="string" name="name"/>
    <var type="string" name="type"/>
    <var type="string" name="var"/>
    <var type="string"  name="doc"/>
    <attr type="string"  name="name" var="name"/>
    <attr type="string"  name="type" var="type"/>
    <attr type="string"  name="var"  var="var"/>
    <attr type="string"  name="doc"  var="doc"/>
  </class>  

  <class name="InfoDoc" elmname="infodoc">
    <doc>This one has documentation for an info-field in a class.</doc>
    <var type="string" name="type"/>
    <var type="string" name="value"/>
    <var type="string"  name="info"/>
    <var type="string"  name="expl"/>

    <attr type="string"  name="type" var="type"/>
    <attr type="string"  name="value" var="value"/>
    <attr type="string"  name="doc"  var="info"/>
    <subelem type="string"  name="expl"  var="expl"/>
  </class>  

  
</api>
